name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # 指定使用的 Node.js 版本

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clean target directory on server
      env:
        SSH_AUTH_SOCK: ${{ secrets.SSH_AUTH_SOCK }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@81.70.198.221 "sudo rm -rf /var/www/example/*"

    - name: Deploy to Server
      env:
        RSYNC_RSH: 'ssh -o StrictHostKeyChecking=no'
      run: |
        rsync -avz --delete ./dist/ ubuntu@81.70.198.221:/var/www/example/
